name: Publish Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # Instalar Jekyll y sus dependencias
      - name: Install Jekyll
        run: |
          gem install bundler jekyll
          bundle init
          bundle add jekyll
          bundle add github-pages

      # Construir el sitio con Jekyll
      - name: Build site
        run: |
          cd Bank/docs
          bundle exec jekyll build --baseurl "" -d ../../_site

      # Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true