name: Publish Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Crear enlace simbólico para que Jekyll encuentre los archivos
      - name: Create symlink from docs to Bank/docs
        run: |
          # Verificar si existe la carpeta docs en la raíz y eliminarla si existe
          if [ -d "docs" ]; then
            rm -rf docs
          fi
          
          # Crear un enlace simbólico de docs a Bank/docs
          ln -s Bank/docs docs
          
          # Verificar que el enlace se creó correctamente
          ls -la
          ls -la docs

      # Construir el sitio con Jekyll usando la acción oficial
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      # Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true