name: Publish Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # Mostrar la estructura de directorios para diagnóstico
      - name: Check directory structure
        run: |
          echo "Checking directory structure..."
          ls -la
          echo "Bank directory contents:"
          ls -la Bank/
          echo "Bank/docs directory contents:"
          ls -la Bank/docs/
          echo "Bank/docs/assets/css directory contents:"
          ls -la Bank/docs/assets/css/

      # Instalar Jekyll y construir el sitio directamente
      - name: Install Jekyll and build site
        run: |
          gem install bundler jekyll
          echo "Creating Gemfile..."
          cat > Gemfile << EOL
          source 'https://rubygems.org'
          gem 'jekyll'
          gem 'github-pages', group: :jekyll_plugins
          EOL
          
          echo "Installing dependencies..."
          bundle install
          
          echo "Building Jekyll site from Bank/docs..."
          cd Bank/docs
          bundle exec jekyll build --baseurl "" -d ../../_site

      # Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true