name: Release Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Paso de diagnóstico super detallado
      - name: Super detailed diagnostic
        run: |
          echo "===== WORKSPACE ROOT CONTENTS ====="
          ls -la
          
          echo "===== CHECKING FOR BANK DIRECTORY (EXACT CASE) ====="
          find . -maxdepth 1 -type d -name "Bank" | wc -l
          
          echo "===== CHECKING FOR ANY CASE OF BANK ====="
          find . -maxdepth 1 -type d -iname "bank" | wc -l
          
          echo "===== LISTING ALL DIRECTORIES ====="
          find . -maxdepth 1 -type d
          
          echo "===== FINDING ALL .SLN FILES IN REPO ====="
          find . -name "*.sln"
          
          echo "===== FINDING ALL .CSPROJ FILES IN REPO ====="
          find . -name "*.csproj"

      # Intento directo con archivos encontrados
      - name: Direct restore with found solution
        run: |
          SOLUTION_FILE=$(find . -name "*.sln" | head -n 1)
          
          if [ -n "$SOLUTION_FILE" ]; then
            echo "Found solution file: $SOLUTION_FILE"
            # Verifica que el archivo existe
            if [ -f "$SOLUTION_FILE" ]; then
              echo "File exists, attempting restore..."
              dotnet restore "$SOLUTION_FILE"
            else
              echo "File doesn't actually exist despite find command"
            fi
          else
            echo "No solution file found in repository"
            
            # Intenta con proyecto en su lugar
            PROJECT_FILE=$(find . -name "*.csproj" | head -n 1)
            if [ -n "$PROJECT_FILE" ]; then
              echo "Found project file: $PROJECT_FILE"
              dotnet restore "$PROJECT_FILE"
            else
              echo "No project files found either"
            fi
          fi

      # Compilación usando archivos encontrados
      - name: Build with found files
        if: success()
        run: |
          SOLUTION_FILE=$(find . -name "*.sln" | head -n 1)
          if [ -n "$SOLUTION_FILE" ]; then
            echo "Building solution: $SOLUTION_FILE"
            dotnet build "$SOLUTION_FILE" --configuration Release
          else
            PROJECT_FILE=$(find . -name "*.csproj" | head -n 1)
            if [ -n "$PROJECT_FILE" ]; then
              echo "Building project: $PROJECT_FILE"
              dotnet build "$PROJECT_FILE" --configuration Release
            fi
          fi

      # Empaquetado con archivos encontrados
      - name: Pack with found files
        if: success()
        run: |
          CSPROJ_FILE=$(find . -name "*.csproj" | head -n 1)
          if [ -n "$CSPROJ_FILE" ]; then
            echo "Packing project: $CSPROJ_FILE"
            dotnet pack "$CSPROJ_FILE" --configuration Release --output nupkg
          else
            echo "No project file found for packing"
          fi

      # Publicación del paquete si existe
      - name: Create GitHub Release
        if: success() && hashFiles('nupkg/*.nupkg') != ''
        uses: softprops/action-gh-release@v2
        with:
          files: nupkg/*.nupkg