name: Release Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Bank/Bank.sln

      - name: Build Release
        run: dotnet build Bank/Bank.sln --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack Bank/Bank.WebApi/Bank.WebApi.csproj --configuration Release --no-build --output nupkg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: nupkg/*.nupkg