name: Semgrep and Prospector Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/csharp
          generateSarif: true
          outputFile: semgrep.json

      # Instalación y ejecución de Prospector
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Este es el paso importante para pasar el test t2
      - name: Install Prospector and generate HTML report
        run: |
          pip install prospector[with_everything]
          
          # Generar el informe HTML usando prospector-html
          pip install prospector-html
          mkdir -p reports
          prospector --output-format json > prospector.json
          prospector-html -i prospector.json -o reports/prospector_report.html
        
      - name: Upload Prospector report
        uses: actions/upload-artifact@v3
        with:
          name: prospector-html-report
          path: reports/prospector_report.html

      # Generar informe HTML de Semgrep
      - name: Generate Semgrep HTML report
        run: |
          echo '<html><head><title>Semgrep Report</title></head><body><pre>' > semgrep-report.html
          cat semgrep.json >> semgrep-report.html
          echo '</pre></body></html>' >> semgrep-report.html

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-html-report
          path: semgrep-report.html